### ISSUE TITLE
URL not accessible anymore?

### ISSUE THREAD

**Issue by jaypizzle** [lukedmor/magnet#1]
I'm getting empty $data (and therefore errors) since quite few days now

**Comment by lorepozo** [comment]
Thanks for reporting the issue! It turns out the search aggregator I use switched from `http` to `https`.

The status code in the response was 301, being redirected to https. I think the http package can handle redirects, but `https` isn't a supported protocol by default.

I've just fixed it a commit.

**Comment by jaypizzle** [comment]
Wow, that was quick!
Thanks - and BTW I love this tool.

**Comment by jaypizzle** [comment]
Sorry - just noticed that listing is fixed but there's still an error when retrieving an actual magnet link (try "magnet ubuntu 1"). Does it work for you?
